old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            use_socket: true
    producers:
        send_sms:
            connection:       default
            exchange_options: { name: 'send-sms', type: direct }
            service_alias:    send_sms_producer
            class:            App\Producer\SendSmsProducer
    consumers:
        send_sms:
            connection:       default
            exchange_options: { name: 'send-sms', type: direct }
            queue_options:    { name: 'send-sms' }
            callback:         App\Consumer\SendSmsConsumer
