version: '3'

services:
    app:
        build: docker/php/.
        container_name: app
        depends_on:
            - db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - DATABASE_URL=mysql://smssender:secret@db:3306/smssender?serverVersion=8
        working_dir: /var/www
        volumes:
            - ./:/var/www

    web:
        image: nginx:alpine
        container_name: web
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/conf.d:/etc/nginx/conf.d

    db:
        image: mysql:8
        container_name: db
        restart: unless-stopped
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=smssender
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=smssender
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:


