version: '3'

services:
    app:
        build: docker/php/.
        container_name: app
        depends_on:
            - db
            - queue
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - DATABASE_URL=mysql://smssender:secret@db:3306/smssender?serverVersion=8
            - RABBITMQ_URL=amqp://guest:guest@queue:5672/smssender?lazy=1&connection_timeout=6
        working_dir: /var/www
        volumes:
            - ./:/var/www

    web:
        image: nginx:alpine
        container_name: web
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/conf.d:/etc/nginx/conf.d

    db:
        image: mysql:8
        container_name: db
        restart: unless-stopped
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=smssender
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=smssender
        volumes:
            - db_data:/var/lib/mysql

    queue:
        image: rabbitmq:management-alpine
        container_name: queue
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_VHOST: smssender
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - queue_data:/var/lib/rabbitmq

volumes:
    db_data:

    queue_data:


